name: auto_route_generator
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/pedrox-hs/flutter_packages
repository: https://github.com/pedrox-hs/flutter_packages/tree/main/auto_route/generator
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: any
  build: any
  collection: any
  source_gen: any
  build_runner: any
  logging: ^1.1.1
  auto_route:
    git:
      url: https://github.com/pedrox-hs/flutter_packages
      path: auto_route
  logify:
    git:
      url: https://github.com/pedrox-hs/flutter_packages
      path: logify

dev_dependencies:
  build_test: any
  lints: any
  source_gen_test: any
  test: any
