name: flutter_toolkit
description: A new Flutter package project.
version: 0.1.1
homepage: https://github.com/pedrox-hs/flutter_packages
repository: https://github.com/pedrox-hs/flutter_packages/tree/main/flutter_toolkit

executables:
  flutter_toolkit: cli

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  dotenv: ^4.0.1
  flutterfire_cli: <1.0.0
  fvm: <3.0.0
  meta: any
  path: any
  process_run: any
  yaml: ^3.1.1

dev_dependencies:
  test: ^1.16.0
  lints: ^5.0.0
