name: logify
description: Just another library for logging
version: 1.0.0
homepage: https://github.com/pedrox-hs/flutter_packages
repository: https://github.com/pedrox-hs/flutter_packages/tree/main/logify

environment:
  sdk: '>=2.12.0'

dependencies:
  logging: '>=1.0.0 <2.0.0'
  meta: ^1.0.0
  stack_trace: ^1.10.0

dev_dependencies: 
  coverage: ^1.7.1
  lints: ^3.0.0
  mocktail: ^1.0.1
  test: ^1.24.2