name: devtools
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/pedrox-hs/flutter_packages
repository: https://github.com/pedrox-hs/flutter_packages/tree/main/devtools

executables:
  devtools: cli

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  dotenv: ^4.0.1
  flutterfire_cli: <1.0.0
  fvm: <3.0.0
  path: any
  process_run: ^0.12.3+2

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0