name: pubspec_gen
description: Code generator for pubspec.yaml info like package name.
version: 0.1.0
homepage: https://github.com/pedrox-hs/flutter_packages
repository: https://github.com/pedrox-hs/flutter_packages/tree/main/pubspec_gen

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  yaml: ^3.1.3
  build: ^2.4.2

dev_dependencies:
  build_test: ^2.2.3
  shared_lints: ^0.1.0
  test: ^1.24.0
