name: auto_route_builder
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/pedrox-hs/flutter_packages
repository: https://github.com/pedrox-hs/flutter_packages/tree/main/auto_route/auto_route_builder

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  analyzer: 
  build:
  collection:
  source_gen:
  auto_route: 0.1.0

dev_dependencies:
  build_test:
  lints:
  source_gen_test:
  test:

dependency_overrides:
  auto_route:
    path: ../auto_route
