name: logger_plus
description: Just another library for logging
version: 1.0.0
homepage: https://github.com/pedrox-hs/flutter_packages
repository: https://github.com/pedrox-hs/flutter_packages/tree/main/logger_plus

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.1.1
  stack_trace: ^1.10.0

dev_dependencies: 
  lints: ^2.0.1
  test: ^1.24.2