name: logger
description: Just another library for logging
version: 0.1.0
homepage: https://github.com/trilobitech/flutter_packages
repository: https://github.com/trilobitech/flutter_packages/tree/main/logger

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: