name: auto_route
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/pedrox-hs/flutter_packages
repository: https://github.com/pedrox-hs/flutter_packages/tree/main/auto_route/auto_route
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  simple_nav: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
