name: auto_route
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/pedrox-hs/flutter_packages
repository: https://github.com/pedrox-hs/flutter_packages/tree/main/auto_route/auto_route
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  simple_nav:
    git:
      url: https://github.com/pedrox-hs/flutter_packages
      path: simple_nav

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
