name: logify_example
description: Logger Plus example
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.1.1
  logify:
    git:
      url: https://github.com/pedrox-hs/flutter_packages
      path: logify