name: Run code static analysis

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        
      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Get dependencies
        run: |
          find . -type f -name pubspec.yaml -execdir flutter pub get \;

      - name: Analyze code
        run: |
          dart analyze --fatal-infos --fatal-warnings

      - name: Check code formatting
        if: always()
        run: |
          dart format --output=none --set-exit-if-changed .
