name: Run automated tests

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:

  find-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.find-packages.outputs.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find packages
        id: find-packages
        run: |
          packages=$(
            find . -type f -name pubspec.yaml -not -path '**/example/*' -exec dirname {} \; \
              | sed -e 's,^\./,,' \
              | sort -u \
              | awk '{print}' ORS='", "')
          echo "packages=[\"${packages::-4}\"]" >> $GITHUB_OUTPUT

  run-tests:
    needs: find-packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.find-packages.outputs.packages) }}
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pub packages
        uses: actions/cache@v4
        if: false
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Check if has Flutter SDK on pubspec.yaml
        id: has-flutter-sdk
        run: |
          if grep -q 'sdk: *flutter' pubspec.yaml; then
            echo "has-flutter-sdk=true" >> $GITHUB_OUTPUT
          else
            echo "has-flutter-sdk=false" >> $GITHUB_OUTPUT
          fi

      - id: versions
        name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1

      - name: Setup Flutter
        if: steps.has-flutter-sdk.outputs.has-flutter-sdk == 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.versions.outputs.flutter }}
          channel: stable
          cache: true

      - name: Setup Dart
        if: steps.has-flutter-sdk.outputs.has-flutter-sdk == 'false'
        uses: dart-lang/setup-dart@v1

      - name: Install Coverage
        if: steps.has-flutter-sdk.outputs.has-flutter-sdk == 'false'
        run: |
          dart pub global activate coverage

      - name: Get package name
        id: package-name
        run: |
          echo "package=$(grep -E '^name:' pubspec.yaml | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          if command -v flutter &> /dev/null; then
            flutter pub get
          else
            dart pub get
          fi

      - name: Ensure test directory exists
        run: |
          mkdir -p test

      - uses: stelynx/dart-full-coverage@v1.1.1
        with:
          use_git_root: false
          main_dir: ${{ matrix.package }}
          package: ${{ steps.package-name.outputs.package }}
          test_file: test/coverage_helper_test.dart

      - name: Add fake test to help coverage
        run: |
          sed -i '/^void main/d' test/coverage_helper_test.dart
          echo -e "import 'package:test/test.dart';\nvoid main(){ test('dart-full-coverage', () {}); }" >> test/coverage_helper_test.dart
          dart pub add test --dev

      - name: Run tests
        run: |
          if command -v test_with_coverage &> /dev/null; then
            test_with_coverage
          else
            flutter test --coverage
          fi

      - name: Normalize Codecov fag name
        id: codecov-flag
        run: |
          echo "name=$(echo ${{ matrix.package }} | sed -e 's/\//./g')" >> $GITHUB_OUTPUT

      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: ${{ steps.codecov-flag.outputs.name }}
          file: ${{ matrix.package }}/coverage/lcov.info
